<?php
return array (
  'site_closed' => '1',
  'site_name' => '链我',
  'site_slogan' => '乐享生活财源',
  'site_header_keywords' => '链我、财源、财源币、红包',
  'site_header_description' => '链我-乐享生活财源',
  'site_company' => '',
  'site_footer' => '©2017  lian wo All  Rights Reserved.',
  'site_footer_des' => '链我-红包社交（享乐生活财源）',
  'attach' => '',
  'site_logo' => '47635',
  'site_qr_code' => '47634',
  'sina_weibo_link' => 'http://weibo.com/ithinksns',
  'login_bg' => '45095',
  'site_closed_reason' => '大伙儿不要害怕，我是来测试功能的，一会儿就给你们恢复，这个页面太丑了我要换一个。',
  'sys_domain' => 'admin,thinksns,kefu,liuxiaoqing,hujintao,liaosunan,xijinping,zhishisoft',
  'sys_nickname' => '管理员,超级管理员,法轮功,胡锦涛,江泽民,邓小平,小秘书,刘晓庆,廖素南,共产党,党,习近平,李宇春,政府,小胡祖宗,国民党,admin,智士软件,thinksns',
  'sys_email' => 'lianwocaiyuan@163.com',
  'home_page' => '0',
  'sys_version' => '2017010101',
  'site_online_count' => '1',
  'site_rewrite_on' => '0',
  'web_closed' => '1',
  'site_analytics_code' => '',
  'logo' => 'http://www.ts.com/resources/theme/stv1/_static/image/logo.png',
  'home_url' => 'http://www.ts.com/index.php?app=public&mod=Index&act=index',
  'site_top_nav' => 
  array (
    1 => 
    array (
      'navi_id' => 1,
      'navi_name' => '首页',
      'app_name' => 'bonus',
      'url' => 'http://www.ts.com/index.php?app=public&mod=Bonus',
      'target' => '_self',
      'status' => 1,
      'position' => '0',
      'guest' => 1,
      'is_app_navi' => 0,
      'parent_id' => 0,
      'order_sort' => 1,
    ),
    4 => 
    array (
      'navi_id' => 4,
      'navi_name' => '自媒体',
      'app_name' => 'zhimeiti',
      'url' => 'http://www.ts.com/index.php?app=weiba',
      'target' => '_self',
      'status' => 1,
      'position' => '0',
      'guest' => 1,
      'is_app_navi' => 0,
      'parent_id' => 0,
      'order_sort' => 2,
    ),
    7 => 
    array (
      'navi_id' => 7,
      'navi_name' => '链我圈',
      'app_name' => 'public',
      'url' => 'http://www.ts.com/index.php?app=public',
      'target' => '_self',
      'status' => 1,
      'position' => '0',
      'guest' => 1,
      'is_app_navi' => 0,
      'parent_id' => 0,
      'order_sort' => 2,
    ),
    11 => 
    array (
      'navi_id' => 11,
      'navi_name' => '找链友',
      'app_name' => 'people',
      'url' => 'http://www.ts.com/index.php?app=people',
      'target' => '_self',
      'status' => 1,
      'position' => '0',
      'guest' => 1,
      'is_app_navi' => 0,
      'parent_id' => 0,
      'order_sort' => 3,
    ),
    2 => 
    array (
      'navi_id' => 2,
      'navi_name' => '频道',
      'app_name' => 'channel',
      'url' => 'http://www.ts.com/index.php?app=channel',
      'target' => '_self',
      'status' => 1,
      'position' => '0',
      'guest' => 1,
      'is_app_navi' => 0,
      'parent_id' => 0,
      'order_sort' => 4,
    ),
  ),
  'site_bottom_nav' => 
  array (
  ),
  'site_bottom_child_nav' => false,
  'site_guest_nav' => 
  array (
    12 => 
    array (
      'navi_id' => 12,
      'navi_name' => '首页',
      'app_name' => 'index',
      'url' => 'http://www.ts.com',
      'target' => '_self',
      'status' => 1,
      'position' => '2',
      'guest' => 1,
      'is_app_navi' => 0,
      'parent_id' => 0,
      'order_sort' => 1,
    ),
    14 => 
    array (
      'navi_id' => 14,
      'navi_name' => '广场',
      'app_name' => 'square',
      'url' => 'http://www.ts.com/index.php?app=square&mod=Index&act=index',
      'target' => '_self',
      'status' => 1,
      'position' => '2',
      'guest' => 1,
      'is_app_navi' => 0,
      'parent_id' => 0,
      'order_sort' => 2,
    ),
  ),
  'search_menu_list' => 
  array (
    0 => 
    array (
      'id' => 1,
      'app_name' => 'public',
      'app_id' => 0,
      'type' => '用户',
      'type_id' => 1,
    ),
    1 => 
    array (
      'id' => 2,
      'app_name' => 'public',
      'app_id' => 0,
      'type' => '分享',
      'type_id' => 2,
    ),
    2 => 
    array (
      'id' => 3,
      'app_name' => 'ask',
      'app_id' => 27,
      'type' => '问答',
      'type_id' => 1,
    ),
  ),
  'site_nav_apps' => 
  array (
    0 => 
    array (
      'app_id' => 30,
      'app_name' => 'Bonusevent',
      'app_alias' => '红包活动',
      'description' => '精彩城市生活，尽在活动！',
      'status' => 1,
      'host_type' => 0,
      'app_entry' => 'http://www.ts.com/index.php?app=Bonusevent&mod=Index&act=index',
      'icon_url' => 'http://www.ts.com/apps/Bonusevent/Appinfo/icon_app.png',
      'large_icon_url' => 'http://www.ts.com/apps/Bonusevent/Appinfo/icon_app_large.png',
      'admin_entry' => 'Bonusevent/Admin/index',
      'statistics_entry' => 'Statistics/statistics',
      'display_order' => 30,
      'ctime' => 1487298766,
      'version' => '1',
      'api_key' => '',
      'secure_key' => '',
      'company_name' => 'Seven Du',
      'has_mobile' => 0,
      'child_menu' => 'a:0:{}',
      'add_front_top' => 1,
      'add_front_applist' => 1,
      'small_icon_url' => 'http://www.ts.com/apps/Bonusevent/Appinfo/icon_app_small.png',
      'iphone_icon' => 'http://www.ts.com/apps/Bonusevent/Appinfo/icon_iphone.png',
      'android_icon' => 'http://www.ts.com/apps/Bonusevent/Appinfo/icon_android.png',
    ),
    1 => 
    array (
      'app_id' => 28,
      'app_name' => 'Information',
      'app_alias' => '今日热闻',
      'description' => '发布新鲜有价值的信息！',
      'status' => 1,
      'host_type' => 0,
      'app_entry' => 'http://www.ts.com/index.php?app=Information&mod=Index&act=index',
      'icon_url' => 'http://www.ts.com/apps/Information/Appinfo/icon_app.png',
      'large_icon_url' => 'http://www.ts.com/apps/Information/Appinfo/icon_app_large.png',
      'admin_entry' => 'Information/Admin/index',
      'statistics_entry' => 'Statistics/statistics',
      'display_order' => 28,
      'ctime' => 1484212392,
      'version' => '1',
      'api_key' => '',
      'secure_key' => '',
      'company_name' => 'lian wo',
      'has_mobile' => 0,
      'child_menu' => 'a:0:{}',
      'add_front_top' => 1,
      'add_front_applist' => 1,
      'small_icon_url' => 'http://www.ts.com/apps/Information/Appinfo/icon_app_small.png',
      'iphone_icon' => 'http://www.ts.com/apps/Information/Appinfo/icon_iphone.png',
      'android_icon' => 'http://www.ts.com/apps/Information/Appinfo/icon_android.png',
    ),
    2 => 
    array (
      'app_id' => 27,
      'app_name' => 'Event',
      'app_alias' => '活动',
      'description' => '精彩城市生活，尽在活动！',
      'status' => 1,
      'host_type' => 0,
      'app_entry' => 'http://www.ts.com/index.php?app=Event&mod=Index&act=index',
      'icon_url' => 'http://www.ts.com/apps/Event/Appinfo/icon_app.png',
      'large_icon_url' => 'http://www.ts.com/apps/Event/Appinfo/icon_app_large.png',
      'admin_entry' => 'Event/Admin/index',
      'statistics_entry' => 'Statistics/statistics',
      'display_order' => 27,
      'ctime' => 1483774347,
      'version' => '1',
      'api_key' => '',
      'secure_key' => '',
      'company_name' => 'Seven Du',
      'has_mobile' => 0,
      'child_menu' => 'a:0:{}',
      'add_front_top' => 1,
      'add_front_applist' => 1,
      'small_icon_url' => 'http://www.ts.com/apps/Event/Appinfo/icon_app_small.png',
      'iphone_icon' => 'http://www.ts.com/apps/Event/Appinfo/icon_iphone.png',
      'android_icon' => 'http://www.ts.com/apps/Event/Appinfo/icon_android.png',
    ),
    3 => 
    array (
      'app_id' => 26,
      'app_name' => 'h5',
      'app_alias' => '链我',
      'description' => '链我-享乐生活财源',
      'status' => 1,
      'host_type' => 0,
      'app_entry' => 'http://www.ts.com/index.php?app=h5&mod=Index&act=index',
      'icon_url' => 'http://www.ts.com/apps/h5/Appinfo/icon_app.png',
      'large_icon_url' => 'http://www.ts.com/apps/h5/Appinfo/icon_app_large.png',
      'admin_entry' => 'h5/Admin/index',
      'statistics_entry' => 'Statistics/statistics',
      'display_order' => 26,
      'ctime' => 1483774318,
      'version' => '1.0.0',
      'api_key' => '',
      'secure_key' => '',
      'company_name' => '链沃科技',
      'has_mobile' => 0,
      'child_menu' => 'a:0:{}',
      'add_front_top' => 1,
      'add_front_applist' => 1,
      'small_icon_url' => 'http://www.ts.com/apps/h5/Appinfo/icon_app_small.png',
      'iphone_icon' => 'http://www.ts.com/apps/h5/Appinfo/icon_iphone.png',
      'android_icon' => 'http://www.ts.com/apps/h5/Appinfo/icon_android.png',
    ),
    4 => 
    array (
      'app_id' => 25,
      'app_name' => 'square',
      'app_alias' => '广场',
      'description' => '',
      'status' => 1,
      'host_type' => 0,
      'app_entry' => 'http://www.ts.com/index.php?app=square&mod=Index&act=index',
      'icon_url' => 'http://www.ts.com/apps/square/Appinfo/icon_app.png',
      'large_icon_url' => 'http://www.ts.com/apps/square/Appinfo/icon_app_large.png',
      'admin_entry' => 'square/Admin/index',
      'statistics_entry' => 'SquareStatistics/statistics',
      'display_order' => 25,
      'ctime' => 1415871528,
      'version' => '',
      'api_key' => '',
      'secure_key' => '',
      'company_name' => '智士软件',
      'has_mobile' => 0,
      'child_menu' => 'a:0:{}',
      'add_front_top' => 1,
      'add_front_applist' => 1,
      'small_icon_url' => 'http://www.ts.com/apps/square/Appinfo/icon_app_small.png',
      'iphone_icon' => 'http://www.ts.com/apps/square/Appinfo/icon_iphone.png',
      'android_icon' => 'http://www.ts.com/apps/square/Appinfo/icon_android.png',
    ),
    5 => 
    array (
      'app_id' => 5,
      'app_name' => 'channel',
      'app_alias' => '频道',
      'description' => '频道',
      'status' => 1,
      'host_type' => 0,
      'app_entry' => 'http://www.ts.com/index.php?app=channel&mod=Index&act=index',
      'icon_url' => 'http://www.ts.com/apps/channel/Appinfo/icon_app.png',
      'large_icon_url' => 'http://www.ts.com/apps/channel/Appinfo/icon_app_large.png',
      'admin_entry' => 'channel/Admin/index',
      'statistics_entry' => 'Statistics/statistics',
      'display_order' => 5,
      'ctime' => 1352520034,
      'version' => '',
      'api_key' => '',
      'secure_key' => '',
      'company_name' => '智士软件',
      'has_mobile' => 1,
      'child_menu' => 'a:0:{}',
      'add_front_top' => 1,
      'add_front_applist' => 1,
      'small_icon_url' => 'http://www.ts.com/apps/channel/Appinfo/icon_app_small.png',
      'iphone_icon' => 'http://www.ts.com/apps/channel/Appinfo/icon_iphone.png',
      'android_icon' => 'http://www.ts.com/apps/channel/Appinfo/icon_android.png',
    ),
    6 => 
    array (
      'app_id' => 4,
      'app_name' => 'people',
      'app_alias' => '找伙伴',
      'description' => '找人',
      'status' => 1,
      'host_type' => 0,
      'app_entry' => 'http://www.ts.com/index.php?app=people&mod=Index&act=index',
      'icon_url' => 'http://www.ts.com/apps/people/Appinfo/icon_app.png',
      'large_icon_url' => 'http://www.ts.com/apps/people/Appinfo/icon_app_large.png',
      'admin_entry' => 'people/Admin/index',
      'statistics_entry' => '',
      'display_order' => 4,
      'ctime' => 1352512423,
      'version' => '',
      'api_key' => '',
      'secure_key' => '',
      'company_name' => '智士软件',
      'has_mobile' => 1,
      'child_menu' => 'a:0:{}',
      'add_front_top' => 1,
      'add_front_applist' => 1,
      'small_icon_url' => 'http://www.ts.com/apps/people/Appinfo/icon_app_small.png',
      'iphone_icon' => 'http://www.ts.com/apps/people/Appinfo/icon_iphone.png',
      'android_icon' => 'http://www.ts.com/apps/people/Appinfo/icon_android.png',
    ),
    7 => 
    array (
      'app_id' => 3,
      'app_name' => 'weiba',
      'app_alias' => '微吧',
      'description' => '微吧',
      'status' => 1,
      'host_type' => 0,
      'app_entry' => 'http://www.ts.com/index.php?app=weiba&mod=Index&act=index',
      'icon_url' => 'http://www.ts.com/apps/weiba/Appinfo/icon_app.png',
      'large_icon_url' => 'http://www.ts.com/apps/weiba/Appinfo/icon_app_large.png',
      'admin_entry' => 'weiba/Admin/index',
      'statistics_entry' => 'Statistics/statistics',
      'display_order' => 3,
      'ctime' => 1352256442,
      'version' => '1.0',
      'api_key' => '',
      'secure_key' => '',
      'company_name' => '智士软件',
      'has_mobile' => 1,
      'child_menu' => 'a:0:{}',
      'add_front_top' => 1,
      'add_front_applist' => 1,
      'small_icon_url' => 'http://www.ts.com/apps/weiba/Appinfo/icon_app_small.png',
      'iphone_icon' => 'http://www.ts.com/apps/weiba/Appinfo/icon_iphone.png',
      'android_icon' => 'http://www.ts.com/apps/weiba/Appinfo/icon_android.png',
    ),
  ),
  'langJsList' => 
  array (
    0 => 'http://www.ts.com/data/lang/public_zh-cn.js',
  ),
  'initNums' => '500',
);
?>